//
//  Pref360StyleKit.m
//  Pref360Control
//
//  Created by Pierre TACCHI on 21/01/15.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "Pref360StyleKit.h"


@implementation Pref360StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawX360ControllerWithControllerNumber: (CGFloat)controllerNumber aPressed: (BOOL)aPressed bPressed: (BOOL)bPressed xPressed: (BOOL)xPressed yPressed: (BOOL)yPressed leftPressed: (BOOL)leftPressed upPressed: (BOOL)upPressed rightPressed: (BOOL)rightPressed downPressed: (BOOL)downPressed backPressed: (BOOL)backPressed startPressed: (BOOL)startPressed lbPressed: (BOOL)lbPressed rbPressed: (BOOL)rbPressed homePressed: (BOOL)homePressed leftStickPressed: (BOOL)leftStickPressed rightStickPressed: (BOOL)rightStickPressed leftStick: (NSPoint)leftStick rightStick: (NSPoint)rightStick
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;

    //// Color Declarations
    NSColor* buttonX = [NSColor colorWithCalibratedRed: 0.124 green: 0.351 blue: 1 alpha: 1];
    NSColor* strokeX = [buttonX shadowWithLevel: 0.5];
    NSColor* buttonA = [NSColor colorWithCalibratedRed: 0.524 green: 0.883 blue: 0 alpha: 1];
    NSColor* strokeA = [buttonA shadowWithLevel: 0.5];
    NSColor* buttonB = [NSColor colorWithCalibratedRed: 1 green: 0.094 blue: 0.072 alpha: 1];
    NSColor* strokeB = [buttonB shadowWithLevel: 0.5];
    NSColor* buttonY = [NSColor colorWithCalibratedRed: 1 green: 0.814 blue: 0.047 alpha: 1];
    NSColor* strokeY = [buttonY shadowWithLevel: 0.5];
    NSColor* buttonHOME = [NSColor colorWithCalibratedRed: 0.895 green: 0.895 blue: 0.895 alpha: 1];
    NSColor* strokeHOME = [buttonHOME shadowWithLevel: 0.5];
    NSColor* controller = [NSColor colorWithCalibratedRed: 0.232 green: 0.232 blue: 0.232 alpha: 1];
    NSColor* backController = [controller highlightWithLevel: 0.4];
    NSColor* darkController = [controller shadowWithLevel: 0.3];
    NSColor* highlightController = [controller highlightWithLevel: 0.1];
    NSColor* stick = [NSColor colorWithCalibratedRed: 0.305 green: 0.335 blue: 0.28 alpha: 1];
    NSColor* highlightStick = [stick highlightWithLevel: 0.3];
    NSColor* shadowStick = [stick shadowWithLevel: 0.2];
    NSColor* pressed = [NSColor colorWithCalibratedRed: 1 green: 0.432 blue: 0 alpha: 1];
    NSColor* pressedStroke = [pressed shadowWithLevel: 0.5];
    NSColor* cross = [NSColor colorWithCalibratedRed: 0.372 green: 0.372 blue: 0.372 alpha: 1];
    NSColor* crossStroke = [cross shadowWithLevel: 0.5];

    //// Variable Declarations
    NSColor* led1Color = controllerNumber == 1 ? buttonA : strokeA;
    NSColor* led2Color = controllerNumber == 2 ? buttonA : strokeA;
    NSColor* led3Color = controllerNumber == 3 ? buttonA : strokeA;
    NSColor* led4Color = controllerNumber == 4 ? buttonA : strokeA;
    NSColor* aColor = aPressed ? pressed : buttonA;
    NSColor* aStroke = aPressed ? pressedStroke : strokeA;
    NSColor* bColor = bPressed ? pressed : buttonB;
    NSColor* bStroke = bPressed ? pressedStroke : strokeB;
    NSColor* xColor = xPressed ? pressed : buttonX;
    NSColor* xStroke = xPressed ? pressedStroke : strokeX;
    NSColor* yColor = yPressed ? pressed : buttonY;
    NSColor* yStroke = yPressed ? pressedStroke : strokeY;
    NSColor* leftColor = leftPressed ? pressed : cross;
    NSColor* leftStroke = leftPressed ? pressedStroke : crossStroke;
    NSColor* upColor = upPressed ? pressed : cross;
    NSColor* upStroke = upPressed ? pressedStroke : crossStroke;
    NSColor* rightColor = rightPressed ? pressed : cross;
    NSColor* rightStroke = rightPressed ? pressedStroke : crossStroke;
    NSColor* downColor = downPressed ? pressed : cross;
    NSColor* downStroke = downPressed ? pressedStroke : crossStroke;
    NSColor* backColor = backPressed ? pressed : controller;
    NSColor* backStroke = backPressed ? pressedStroke : darkController;
    NSColor* startColor = startPressed ? pressed : controller;
    NSColor* startStroke = startPressed ? pressedStroke : darkController;
    NSColor* lbColor = lbPressed ? pressed : darkController;
    CGFloat leftAngle = lbPressed ? 2.5 : 0;
    NSColor* rbColor = rbPressed ? pressed : darkController;
    CGFloat rightAngle = rbPressed ? -2.5 : 0;
    NSColor* homeColor = homePressed ? pressed : buttonHOME;
    NSColor* homeStroke = homePressed ? pressedStroke : strokeHOME;
    NSColor* leftStickColor = leftStickPressed ? pressed : stick;
    NSColor* leftStickStroke = leftStickPressed ? pressedStroke : shadowStick;
    NSColor* rightStickColor = rightStickPressed ? pressed : stick;
    NSColor* rightStickStroke = rightStickPressed ? pressedStroke : shadowStick;
    NSPoint leftStickPosition = NSMakePoint(leftStick.x * 10 + 69, -leftStick.y * 10 + 155);
    CGFloat leftXScale = 1 - 0.1 * fabs(leftStick.x);
    CGFloat leftYScale = 1 - 0.1 * fabs(leftStick.y);
    NSPoint rightStickPosition2 = NSMakePoint(rightStick.x * 10 + 195, -rightStick.y * 10 + 104);

    //// right shoulder Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 211.42, 183.5);
    CGContextRotateCTM(context, rightAngle * M_PI / 180);

    NSBezierPath* rightShoulderPath = NSBezierPath.bezierPath;
    [rightShoulderPath moveToPoint: NSMakePoint(51.27, 1.89)];
    [rightShoulderPath curveToPoint: NSMakePoint(50.51, 10.3) controlPoint1: NSMakePoint(51.77, 9.89) controlPoint2: NSMakePoint(51.4, 8.19)];
    [rightShoulderPath curveToPoint: NSMakePoint(27.08, 21.61) controlPoint1: NSMakePoint(49.61, 12.4) controlPoint2: NSMakePoint(35.66, 20.13)];
    [rightShoulderPath curveToPoint: NSMakePoint(4.43, 22.72) controlPoint1: NSMakePoint(18.5, 23.09) controlPoint2: NSMakePoint(8.95, 24.07)];
    [rightShoulderPath curveToPoint: NSMakePoint(2.52, 18.78) controlPoint1: NSMakePoint(4.8, 19.97) controlPoint2: NSMakePoint(2.52, 18.78)];
    [rightShoulderPath lineToPoint: NSMakePoint(1, 17.67)];
    [rightShoulderPath lineToPoint: NSMakePoint(3.29, 13.85)];
    [rightShoulderPath curveToPoint: NSMakePoint(51.27, 1.89) controlPoint1: NSMakePoint(3.29, 13.85) controlPoint2: NSMakePoint(50.77, -6.11)];
    [rightShoulderPath closePath];
    [rbColor setFill];
    [rightShoulderPath fill];

    [NSGraphicsContext restoreGraphicsState];


    //// leftShoulder Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 96.92, 183.5);
    CGContextRotateCTM(context, leftAngle * M_PI / 180);

    NSBezierPath* leftShoulderPath = NSBezierPath.bezierPath;
    [leftShoulderPath moveToPoint: NSMakePoint(-51.27, 1.89)];
    [leftShoulderPath curveToPoint: NSMakePoint(-50.51, 10.3) controlPoint1: NSMakePoint(-51.77, 9.89) controlPoint2: NSMakePoint(-51.4, 8.19)];
    [leftShoulderPath curveToPoint: NSMakePoint(-27.08, 21.61) controlPoint1: NSMakePoint(-49.61, 12.4) controlPoint2: NSMakePoint(-35.66, 20.13)];
    [leftShoulderPath curveToPoint: NSMakePoint(-4.43, 22.72) controlPoint1: NSMakePoint(-18.5, 23.09) controlPoint2: NSMakePoint(-8.95, 24.07)];
    [leftShoulderPath curveToPoint: NSMakePoint(-2.52, 18.78) controlPoint1: NSMakePoint(-4.8, 19.97) controlPoint2: NSMakePoint(-2.52, 18.78)];
    [leftShoulderPath lineToPoint: NSMakePoint(-1, 17.67)];
    [leftShoulderPath lineToPoint: NSMakePoint(-3.29, 13.85)];
    [leftShoulderPath curveToPoint: NSMakePoint(-51.27, 1.89) controlPoint1: NSMakePoint(-3.29, 13.85) controlPoint2: NSMakePoint(-50.77, -6.11)];
    [leftShoulderPath closePath];
    [lbColor setFill];
    [leftShoulderPath fill];

    [NSGraphicsContext restoreGraphicsState];


    //// body
    {
        //// underPiece Drawing
        NSBezierPath* underPiecePath = NSBezierPath.bezierPath;
        [underPiecePath moveToPoint: NSMakePoint(154.42, 54.67)];
        [underPiecePath curveToPoint: NSMakePoint(170.84, 54.61) controlPoint1: NSMakePoint(154.42, 54.67) controlPoint2: NSMakePoint(160.14, 54.67)];
        [underPiecePath curveToPoint: NSMakePoint(196.84, 51.3) controlPoint1: NSMakePoint(181.55, 54.55) controlPoint2: NSMakePoint(189.59, 53.73)];
        [underPiecePath curveToPoint: NSMakePoint(223.47, 36.26) controlPoint1: NSMakePoint(204.08, 48.87) controlPoint2: NSMakePoint(214.61, 45.12)];
        [underPiecePath curveToPoint: NSMakePoint(258.79, 7.11) controlPoint1: NSMakePoint(232.33, 27.4) controlPoint2: NSMakePoint(251.78, 10.43)];
        [underPiecePath curveToPoint: NSMakePoint(279.22, 3.24) controlPoint1: NSMakePoint(265.8, 3.79) controlPoint2: NSMakePoint(273.32, 3.24)];
        [underPiecePath curveToPoint: NSMakePoint(256.9, 18.31) controlPoint1: NSMakePoint(285.13, 3.24) controlPoint2: NSMakePoint(256.9, 18.31)];
        [underPiecePath lineToPoint: NSMakePoint(224.36, 46.91)];
        [underPiecePath lineToPoint: NSMakePoint(202.16, 59.45)];
        [underPiecePath lineToPoint: NSMakePoint(154.42, 66.63)];
        [underPiecePath lineToPoint: NSMakePoint(106.68, 59.45)];
        [underPiecePath lineToPoint: NSMakePoint(84.47, 46.91)];
        [underPiecePath lineToPoint: NSMakePoint(51.94, 18.31)];
        [underPiecePath curveToPoint: NSMakePoint(29.61, 3.24) controlPoint1: NSMakePoint(51.94, 18.31) controlPoint2: NSMakePoint(23.71, 3.24)];
        [underPiecePath curveToPoint: NSMakePoint(50.05, 7.11) controlPoint1: NSMakePoint(35.52, 3.24) controlPoint2: NSMakePoint(43.04, 3.79)];
        [underPiecePath curveToPoint: NSMakePoint(85.37, 36.26) controlPoint1: NSMakePoint(57.06, 10.43) controlPoint2: NSMakePoint(76.51, 27.4)];
        [underPiecePath curveToPoint: NSMakePoint(112, 51.3) controlPoint1: NSMakePoint(94.22, 45.12) controlPoint2: NSMakePoint(104.75, 48.87)];
        [underPiecePath curveToPoint: NSMakePoint(137.99, 54.61) controlPoint1: NSMakePoint(119.24, 53.73) controlPoint2: NSMakePoint(127.29, 54.55)];
        [underPiecePath curveToPoint: NSMakePoint(154.42, 54.67) controlPoint1: NSMakePoint(148.69, 54.67) controlPoint2: NSMakePoint(154.42, 54.67)];
        [underPiecePath closePath];
        [backController setFill];
        [underPiecePath fill];


        //// upperPiece Drawing
        NSBezierPath* upperPiecePath = NSBezierPath.bezierPath;
        [upperPiecePath moveToPoint: NSMakePoint(216.95, 193.26)];
        [upperPiecePath lineToPoint: NSMakePoint(211.08, 200.86)];
        [upperPiecePath curveToPoint: NSMakePoint(190.84, 191.99) controlPoint1: NSMakePoint(211.08, 200.86) controlPoint2: NSMakePoint(197.85, 194.11)];
        [upperPiecePath curveToPoint: NSMakePoint(170.6, 189.32) controlPoint1: NSMakePoint(183.83, 189.87) controlPoint2: NSMakePoint(176.6, 189.32)];
        [upperPiecePath curveToPoint: NSMakePoint(154.2, 189.32) controlPoint1: NSMakePoint(164.61, 189.32) controlPoint2: NSMakePoint(154.2, 189.32)];
        [upperPiecePath curveToPoint: NSMakePoint(137.8, 189.32) controlPoint1: NSMakePoint(154.2, 189.32) controlPoint2: NSMakePoint(143.8, 189.32)];
        [upperPiecePath curveToPoint: NSMakePoint(117.57, 191.99) controlPoint1: NSMakePoint(131.81, 189.32) controlPoint2: NSMakePoint(124.58, 189.87)];
        [upperPiecePath curveToPoint: NSMakePoint(97.33, 200.86) controlPoint1: NSMakePoint(110.56, 194.11) controlPoint2: NSMakePoint(97.33, 200.86)];
        [upperPiecePath lineToPoint: NSMakePoint(91.45, 193.26)];
        [upperPiecePath lineToPoint: NSMakePoint(103.15, 180.34)];
        [upperPiecePath lineToPoint: NSMakePoint(154.2, 169.64)];
        [upperPiecePath lineToPoint: NSMakePoint(211.08, 180.34)];
        [upperPiecePath lineToPoint: NSMakePoint(216.95, 193.26)];
        [upperPiecePath closePath];
        [darkController setFill];
        [upperPiecePath fill];


        //// mainPiece Drawing
        NSBezierPath* mainPiecePath = NSBezierPath.bezierPath;
        [mainPiecePath moveToPoint: NSMakePoint(154.42, 60.17)];
        [mainPiecePath curveToPoint: NSMakePoint(132.73, 60.18) controlPoint1: NSMakePoint(154.42, 60.17) controlPoint2: NSMakePoint(145.73, 60.18)];
        [mainPiecePath curveToPoint: NSMakePoint(92.17, 48.92) controlPoint1: NSMakePoint(119.73, 60.18) controlPoint2: NSMakePoint(103.94, 57.43)];
        [mainPiecePath curveToPoint: NSMakePoint(63.42, 23.8) controlPoint1: NSMakePoint(80.39, 40.41) controlPoint2: NSMakePoint(72.2, 32.58)];
        [mainPiecePath curveToPoint: NSMakePoint(38.17, 3.92) controlPoint1: NSMakePoint(54.63, 15.01) controlPoint2: NSMakePoint(42.64, 5.44)];
        [mainPiecePath curveToPoint: NSMakePoint(21.41, 4.7) controlPoint1: NSMakePoint(33.69, 2.4) controlPoint2: NSMakePoint(25.03, 2.84)];
        [mainPiecePath curveToPoint: NSMakePoint(12.85, 14.19) controlPoint1: NSMakePoint(17.79, 6.56) controlPoint2: NSMakePoint(15.68, 8.84)];
        [mainPiecePath curveToPoint: NSMakePoint(7.81, 32.22) controlPoint1: NSMakePoint(10.02, 19.54) controlPoint2: NSMakePoint(8.86, 24.26)];
        [mainPiecePath curveToPoint: NSMakePoint(7.93, 63.99) controlPoint1: NSMakePoint(6.77, 40.18) controlPoint2: NSMakePoint(6.59, 50.59)];
        [mainPiecePath curveToPoint: NSMakePoint(12.41, 95.17) controlPoint1: NSMakePoint(9.26, 77.39) controlPoint2: NSMakePoint(10.17, 82.67)];
        [mainPiecePath curveToPoint: NSMakePoint(22.23, 133.61) controlPoint1: NSMakePoint(14.64, 107.66) controlPoint2: NSMakePoint(18.46, 121.04)];
        [mainPiecePath curveToPoint: NSMakePoint(34.62, 169.17) controlPoint1: NSMakePoint(26, 146.18) controlPoint2: NSMakePoint(32.03, 162.27)];
        [mainPiecePath curveToPoint: NSMakePoint(44.9, 189.48) controlPoint1: NSMakePoint(37.2, 176.06) controlPoint2: NSMakePoint(40.64, 185.95)];
        [mainPiecePath curveToPoint: NSMakePoint(66.23, 199.9) controlPoint1: NSMakePoint(49.16, 193) controlPoint2: NSMakePoint(56.63, 197.13)];
        [mainPiecePath curveToPoint: NSMakePoint(90.89, 201.9) controlPoint1: NSMakePoint(75.82, 202.66) controlPoint2: NSMakePoint(86.58, 202.7)];
        [mainPiecePath curveToPoint: NSMakePoint(102.07, 196.32) controlPoint1: NSMakePoint(95.19, 201.1) controlPoint2: NSMakePoint(96.65, 200.01)];
        [mainPiecePath curveToPoint: NSMakePoint(114.84, 188.02) controlPoint1: NSMakePoint(107.49, 192.63) controlPoint2: NSMakePoint(110.56, 190.14)];
        [mainPiecePath curveToPoint: NSMakePoint(132.34, 183.04) controlPoint1: NSMakePoint(119.11, 185.91) controlPoint2: NSMakePoint(124.89, 183.96)];
        [mainPiecePath curveToPoint: NSMakePoint(154.42, 181.67) controlPoint1: NSMakePoint(139.79, 182.12) controlPoint2: NSMakePoint(150.24, 181.73)];
        [mainPiecePath curveToPoint: NSMakePoint(176.5, 183.04) controlPoint1: NSMakePoint(158.6, 181.73) controlPoint2: NSMakePoint(169.05, 182.12)];
        [mainPiecePath curveToPoint: NSMakePoint(194, 188.02) controlPoint1: NSMakePoint(183.94, 183.96) controlPoint2: NSMakePoint(189.72, 185.91)];
        [mainPiecePath curveToPoint: NSMakePoint(206.77, 196.32) controlPoint1: NSMakePoint(198.27, 190.14) controlPoint2: NSMakePoint(201.35, 192.63)];
        [mainPiecePath curveToPoint: NSMakePoint(217.95, 201.9) controlPoint1: NSMakePoint(212.18, 200.01) controlPoint2: NSMakePoint(213.64, 201.1)];
        [mainPiecePath curveToPoint: NSMakePoint(242.61, 199.9) controlPoint1: NSMakePoint(222.25, 202.7) controlPoint2: NSMakePoint(233.01, 202.66)];
        [mainPiecePath curveToPoint: NSMakePoint(263.94, 189.48) controlPoint1: NSMakePoint(252.2, 197.13) controlPoint2: NSMakePoint(259.68, 193)];
        [mainPiecePath curveToPoint: NSMakePoint(274.22, 169.17) controlPoint1: NSMakePoint(268.2, 185.95) controlPoint2: NSMakePoint(271.64, 176.06)];
        [mainPiecePath curveToPoint: NSMakePoint(286.61, 133.61) controlPoint1: NSMakePoint(276.8, 162.27) controlPoint2: NSMakePoint(282.84, 146.18)];
        [mainPiecePath curveToPoint: NSMakePoint(296.43, 95.17) controlPoint1: NSMakePoint(290.38, 121.04) controlPoint2: NSMakePoint(294.19, 107.66)];
        [mainPiecePath curveToPoint: NSMakePoint(300.91, 63.99) controlPoint1: NSMakePoint(298.67, 82.67) controlPoint2: NSMakePoint(299.58, 77.39)];
        [mainPiecePath curveToPoint: NSMakePoint(301.02, 32.22) controlPoint1: NSMakePoint(302.24, 50.59) controlPoint2: NSMakePoint(302.06, 40.18)];
        [mainPiecePath curveToPoint: NSMakePoint(295.99, 14.19) controlPoint1: NSMakePoint(299.98, 24.26) controlPoint2: NSMakePoint(298.82, 19.54)];
        [mainPiecePath curveToPoint: NSMakePoint(287.43, 4.7) controlPoint1: NSMakePoint(293.15, 8.84) controlPoint2: NSMakePoint(291.04, 6.56)];
        [mainPiecePath curveToPoint: NSMakePoint(270.67, 3.92) controlPoint1: NSMakePoint(283.81, 2.84) controlPoint2: NSMakePoint(275.14, 2.4)];
        [mainPiecePath curveToPoint: NSMakePoint(245.42, 23.8) controlPoint1: NSMakePoint(266.19, 5.44) controlPoint2: NSMakePoint(255.15, 14.37)];
        [mainPiecePath curveToPoint: NSMakePoint(216.67, 48.92) controlPoint1: NSMakePoint(235.69, 33.23) controlPoint2: NSMakePoint(228.44, 40.41)];
        [mainPiecePath curveToPoint: NSMakePoint(176.1, 60.18) controlPoint1: NSMakePoint(204.89, 57.43) controlPoint2: NSMakePoint(189.1, 60.18)];
        [mainPiecePath curveToPoint: NSMakePoint(154.42, 60.17) controlPoint1: NSMakePoint(163.1, 60.18) controlPoint2: NSMakePoint(154.42, 60.17)];
        [mainPiecePath closePath];
        [controller setFill];
        [mainPiecePath fill];


        //// Bezier 6 Drawing
        NSBezierPath* bezier6Path = NSBezierPath.bezierPath;
        [bezier6Path moveToPoint: NSMakePoint(90.89, 201.9)];
        [bezier6Path curveToPoint: NSMakePoint(102.07, 196.32) controlPoint1: NSMakePoint(95.19, 201.1) controlPoint2: NSMakePoint(96.65, 200.01)];
        [bezier6Path curveToPoint: NSMakePoint(114.84, 188.02) controlPoint1: NSMakePoint(107.49, 192.63) controlPoint2: NSMakePoint(110.56, 190.14)];
        [bezier6Path curveToPoint: NSMakePoint(132.34, 183.04) controlPoint1: NSMakePoint(119.11, 185.91) controlPoint2: NSMakePoint(124.89, 183.96)];
        [bezier6Path curveToPoint: NSMakePoint(154.42, 181.67) controlPoint1: NSMakePoint(139.79, 182.12) controlPoint2: NSMakePoint(150.24, 181.73)];
        [bezier6Path curveToPoint: NSMakePoint(176.5, 183.04) controlPoint1: NSMakePoint(158.6, 181.73) controlPoint2: NSMakePoint(169.05, 182.12)];
        [bezier6Path curveToPoint: NSMakePoint(194, 188.02) controlPoint1: NSMakePoint(183.94, 183.96) controlPoint2: NSMakePoint(189.72, 185.91)];
        [bezier6Path curveToPoint: NSMakePoint(206.77, 196.32) controlPoint1: NSMakePoint(198.27, 190.14) controlPoint2: NSMakePoint(201.35, 192.63)];
        [bezier6Path curveToPoint: NSMakePoint(217.95, 201.9) controlPoint1: NSMakePoint(212.18, 200.01) controlPoint2: NSMakePoint(213.64, 201.1)];
        [bezier6Path curveToPoint: NSMakePoint(242.61, 199.9) controlPoint1: NSMakePoint(222.25, 202.7) controlPoint2: NSMakePoint(233.01, 202.66)];
        [bezier6Path curveToPoint: NSMakePoint(263.94, 189.48) controlPoint1: NSMakePoint(252.2, 197.13) controlPoint2: NSMakePoint(259.68, 193)];
        [bezier6Path curveToPoint: NSMakePoint(266.39, 186.69) controlPoint1: NSMakePoint(264.79, 188.78) controlPoint2: NSMakePoint(265.6, 187.82)];
        [bezier6Path curveToPoint: NSMakePoint(228.85, 197.96) controlPoint1: NSMakePoint(254.6, 191.7) controlPoint2: NSMakePoint(239.33, 197.92)];
        [bezier6Path curveToPoint: NSMakePoint(202.52, 187.88) controlPoint1: NSMakePoint(216.01, 198) controlPoint2: NSMakePoint(212.22, 194.78)];
        [bezier6Path curveToPoint: NSMakePoint(173.97, 176.68) controlPoint1: NSMakePoint(192.81, 180.98) controlPoint2: NSMakePoint(183.21, 177.29)];
        [bezier6Path curveToPoint: NSMakePoint(161.63, 176.35) controlPoint1: NSMakePoint(169.79, 176.4) controlPoint2: NSMakePoint(165.29, 176.34)];
        [bezier6Path curveToPoint: NSMakePoint(154.2, 176.35) controlPoint1: NSMakePoint(157.2, 176.37) controlPoint2: NSMakePoint(154.2, 176.35)];
        [bezier6Path curveToPoint: NSMakePoint(146.78, 176.35) controlPoint1: NSMakePoint(154.2, 176.35) controlPoint2: NSMakePoint(151.21, 176.37)];
        [bezier6Path curveToPoint: NSMakePoint(134.43, 176.68) controlPoint1: NSMakePoint(143.11, 176.34) controlPoint2: NSMakePoint(138.62, 176.4)];
        [bezier6Path curveToPoint: NSMakePoint(105.89, 187.88) controlPoint1: NSMakePoint(125.19, 177.29) controlPoint2: NSMakePoint(115.6, 180.98)];
        [bezier6Path curveToPoint: NSMakePoint(79.55, 197.96) controlPoint1: NSMakePoint(96.18, 194.78) controlPoint2: NSMakePoint(92.4, 198)];
        [bezier6Path curveToPoint: NSMakePoint(42.63, 186.95) controlPoint1: NSMakePoint(69.26, 197.92) controlPoint2: NSMakePoint(54.33, 191.91)];
        [bezier6Path curveToPoint: NSMakePoint(44.9, 189.48) controlPoint1: NSMakePoint(43.36, 187.97) controlPoint2: NSMakePoint(44.11, 188.83)];
        [bezier6Path curveToPoint: NSMakePoint(66.23, 199.9) controlPoint1: NSMakePoint(49.16, 193) controlPoint2: NSMakePoint(56.63, 197.13)];
        [bezier6Path curveToPoint: NSMakePoint(90.89, 201.9) controlPoint1: NSMakePoint(75.82, 202.66) controlPoint2: NSMakePoint(86.58, 202.7)];
        [bezier6Path closePath];
        [highlightController setFill];
        [bezier6Path fill];


        //// Oval Drawing
        NSBezierPath* ovalPath = NSBezierPath.bezierPath;
        [ovalPath moveToPoint: NSMakePoint(217.48, 76.81)];
        [ovalPath curveToPoint: NSMakePoint(217.48, 124.19) controlPoint1: NSMakePoint(230.17, 89.89) controlPoint2: NSMakePoint(230.17, 111.11)];
        [ovalPath curveToPoint: NSMakePoint(171.52, 124.19) controlPoint1: NSMakePoint(204.79, 137.27) controlPoint2: NSMakePoint(184.21, 137.27)];
        [ovalPath curveToPoint: NSMakePoint(171.52, 76.81) controlPoint1: NSMakePoint(158.83, 111.11) controlPoint2: NSMakePoint(158.83, 89.89)];
        [ovalPath curveToPoint: NSMakePoint(217.48, 76.81) controlPoint1: NSMakePoint(184.21, 63.73) controlPoint2: NSMakePoint(204.79, 63.73)];
        [ovalPath closePath];
        [darkController setStroke];
        [ovalPath setLineWidth: 1];
        [ovalPath stroke];


        //// Oval 4 Drawing
        NSBezierPath* oval4Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(38, 124, 61.47, 60.74)];
        [darkController setStroke];
        [oval4Path setLineWidth: 1];
        [oval4Path stroke];


        //// Oval 2 Drawing
        NSBezierPath* oval2Path = NSBezierPath.bezierPath;
        [oval2Path moveToPoint: NSMakePoint(133.01, 78.29)];
        [oval2Path curveToPoint: NSMakePoint(133.01, 125.53) controlPoint1: NSMakePoint(145.94, 91.34) controlPoint2: NSMakePoint(145.94, 112.49)];
        [oval2Path curveToPoint: NSMakePoint(86.16, 125.53) controlPoint1: NSMakePoint(120.07, 138.58) controlPoint2: NSMakePoint(99.09, 138.58)];
        [oval2Path curveToPoint: NSMakePoint(86.16, 78.29) controlPoint1: NSMakePoint(73.22, 112.49) controlPoint2: NSMakePoint(73.22, 91.34)];
        [oval2Path curveToPoint: NSMakePoint(133.01, 78.29) controlPoint1: NSMakePoint(99.09, 65.25) controlPoint2: NSMakePoint(120.07, 65.25)];
        [oval2Path closePath];
        [darkController setStroke];
        [oval2Path setLineWidth: 1];
        [oval2Path stroke];
    }


    //// home Drawing
    NSBezierPath* homePath = NSBezierPath.bezierPath;
    [homePath moveToPoint: NSMakePoint(166.92, 150.67)];
    [homePath curveToPoint: NSMakePoint(154.42, 163.17) controlPoint1: NSMakePoint(166.92, 157.57) controlPoint2: NSMakePoint(161.32, 163.17)];
    [homePath curveToPoint: NSMakePoint(141.92, 150.67) controlPoint1: NSMakePoint(147.51, 163.17) controlPoint2: NSMakePoint(141.92, 157.57)];
    [homePath curveToPoint: NSMakePoint(154.42, 138.17) controlPoint1: NSMakePoint(141.92, 143.77) controlPoint2: NSMakePoint(147.51, 138.17)];
    [homePath curveToPoint: NSMakePoint(166.92, 150.67) controlPoint1: NSMakePoint(161.32, 138.17) controlPoint2: NSMakePoint(166.92, 143.77)];
    [homePath closePath];
    [homeColor setFill];
    [homePath fill];
    [homeStroke setStroke];
    [homePath setLineWidth: 1];
    [homePath stroke];


    //// Group 2
    {
        //// back Drawing
        NSBezierPath* backPath = NSBezierPath.bezierPath;
        [backPath moveToPoint: NSMakePoint(131.42, 151.17)];
        [backPath curveToPoint: NSMakePoint(125.39, 144.25) controlPoint1: NSMakePoint(131.42, 147.67) controlPoint2: NSMakePoint(128.81, 144.78)];
        [backPath curveToPoint: NSMakePoint(124.28, 144.17) controlPoint1: NSMakePoint(125.03, 144.2) controlPoint2: NSMakePoint(124.66, 144.17)];
        [backPath curveToPoint: NSMakePoint(122.06, 144.17) controlPoint1: NSMakePoint(124.28, 144.17) controlPoint2: NSMakePoint(122.43, 144.17)];
        [backPath curveToPoint: NSMakePoint(114.92, 151.17) controlPoint1: NSMakePoint(118.11, 144.17) controlPoint2: NSMakePoint(114.92, 147.3)];
        [backPath curveToPoint: NSMakePoint(122.06, 158.17) controlPoint1: NSMakePoint(114.92, 155.03) controlPoint2: NSMakePoint(118.11, 158.17)];
        [backPath curveToPoint: NSMakePoint(124.28, 158.17) controlPoint1: NSMakePoint(122.43, 158.17) controlPoint2: NSMakePoint(123.9, 158.17)];
        [backPath curveToPoint: NSMakePoint(131.42, 151.17) controlPoint1: NSMakePoint(128.22, 158.17) controlPoint2: NSMakePoint(131.42, 155.03)];
        [backPath closePath];
        [backColor setFill];
        [backPath fill];
        [backStroke setStroke];
        [backPath setLineWidth: 1];
        [backPath stroke];


        //// Rectangle Drawing
        NSBezierPath* rectanglePath = NSBezierPath.bezierPath;
        [rectanglePath moveToPoint: NSMakePoint(124.97, 154.37)];
        [rectanglePath lineToPoint: NSMakePoint(119.77, 151.17)];
        [rectanglePath lineToPoint: NSMakePoint(124.97, 147.97)];
        [rectanglePath lineToPoint: NSMakePoint(124.97, 154.37)];
        [rectanglePath closePath];
        [backStroke setFill];
        [rectanglePath fill];
    }


    //// Group 3
    {
        //// start Drawing
        NSBezierPath* startPath = NSBezierPath.bezierPath;
        [startPath moveToPoint: NSMakePoint(192.87, 151.17)];
        [startPath curveToPoint: NSMakePoint(186.85, 144.25) controlPoint1: NSMakePoint(192.87, 147.67) controlPoint2: NSMakePoint(190.26, 144.78)];
        [startPath curveToPoint: NSMakePoint(185.74, 144.17) controlPoint1: NSMakePoint(186.49, 144.2) controlPoint2: NSMakePoint(186.11, 144.17)];
        [startPath curveToPoint: NSMakePoint(183.51, 144.17) controlPoint1: NSMakePoint(185.74, 144.17) controlPoint2: NSMakePoint(183.89, 144.17)];
        [startPath curveToPoint: NSMakePoint(176.37, 151.17) controlPoint1: NSMakePoint(179.57, 144.17) controlPoint2: NSMakePoint(176.37, 147.3)];
        [startPath curveToPoint: NSMakePoint(183.51, 158.17) controlPoint1: NSMakePoint(176.37, 155.03) controlPoint2: NSMakePoint(179.57, 158.17)];
        [startPath curveToPoint: NSMakePoint(185.74, 158.17) controlPoint1: NSMakePoint(183.89, 158.17) controlPoint2: NSMakePoint(185.36, 158.17)];
        [startPath curveToPoint: NSMakePoint(192.87, 151.17) controlPoint1: NSMakePoint(189.68, 158.17) controlPoint2: NSMakePoint(192.87, 155.03)];
        [startPath closePath];
        [startColor setFill];
        [startPath fill];
        [startStroke setStroke];
        [startPath setLineWidth: 1];
        [startPath stroke];


        //// Rectangle 2 Drawing
        NSBezierPath* rectangle2Path = NSBezierPath.bezierPath;
        [rectangle2Path moveToPoint: NSMakePoint(182.82, 147.97)];
        [rectangle2Path lineToPoint: NSMakePoint(188.02, 151.17)];
        [rectangle2Path lineToPoint: NSMakePoint(182.82, 154.37)];
        [rectangle2Path lineToPoint: NSMakePoint(182.82, 147.97)];
        [rectangle2Path closePath];
        [startStroke setFill];
        [rectangle2Path fill];
    }


    //// Group 4
    {
        //// Bezier Drawing
        NSBezierPath* bezierPath = NSBezierPath.bezierPath;
        [bezierPath moveToPoint: NSMakePoint(152.42, 168.64)];
        [bezierPath curveToPoint: NSMakePoint(152.42, 167.47) controlPoint1: NSMakePoint(152.42, 168.32) controlPoint2: NSMakePoint(152.42, 167.93)];
        [bezierPath curveToPoint: NSMakePoint(152.42, 165.34) controlPoint1: NSMakePoint(152.42, 166.87) controlPoint2: NSMakePoint(152.42, 166.15)];
        [bezierPath curveToPoint: NSMakePoint(139.75, 152.67) controlPoint1: NSMakePoint(145.63, 164.88) controlPoint2: NSMakePoint(140.21, 159.45)];
        [bezierPath lineToPoint: NSMakePoint(136.45, 152.67)];
        [bezierPath curveToPoint: NSMakePoint(152.42, 168.64) controlPoint1: NSMakePoint(136.92, 161.27) controlPoint2: NSMakePoint(143.81, 168.17)];
        [bezierPath closePath];
        [led1Color setFill];
        [bezierPath fill];


        //// Bezier 3 Drawing
        NSBezierPath* bezier3Path = NSBezierPath.bezierPath;
        [bezier3Path moveToPoint: NSMakePoint(156.42, 168.64)];
        [bezier3Path curveToPoint: NSMakePoint(172.39, 152.67) controlPoint1: NSMakePoint(165.02, 168.17) controlPoint2: NSMakePoint(171.92, 161.27)];
        [bezier3Path curveToPoint: NSMakePoint(169.09, 152.67) controlPoint1: NSMakePoint(171.62, 152.67) controlPoint2: NSMakePoint(170.45, 152.67)];
        [bezier3Path curveToPoint: NSMakePoint(156.42, 165.34) controlPoint1: NSMakePoint(168.63, 159.45) controlPoint2: NSMakePoint(163.2, 164.88)];
        [bezier3Path curveToPoint: NSMakePoint(156.42, 168.64) controlPoint1: NSMakePoint(156.42, 166.76) controlPoint2: NSMakePoint(156.42, 167.9)];
        [bezier3Path closePath];
        [led2Color setFill];
        [bezier3Path fill];


        //// Bezier 2 Drawing
        NSBezierPath* bezier2Path = NSBezierPath.bezierPath;
        [bezier2Path moveToPoint: NSMakePoint(172.39, 148.67)];
        [bezier2Path curveToPoint: NSMakePoint(156.42, 132.7) controlPoint1: NSMakePoint(171.92, 140.06) controlPoint2: NSMakePoint(165.02, 133.17)];
        [bezier2Path curveToPoint: NSMakePoint(156.42, 136) controlPoint1: NSMakePoint(156.42, 133.44) controlPoint2: NSMakePoint(156.42, 134.58)];
        [bezier2Path curveToPoint: NSMakePoint(169.09, 148.67) controlPoint1: NSMakePoint(163.2, 136.46) controlPoint2: NSMakePoint(168.63, 141.88)];
        [bezier2Path lineToPoint: NSMakePoint(172.39, 148.67)];
        [bezier2Path closePath];
        [led4Color setFill];
        [bezier2Path fill];


        //// Bezier 4 Drawing
        NSBezierPath* bezier4Path = NSBezierPath.bezierPath;
        [bezier4Path moveToPoint: NSMakePoint(136.45, 148.67)];
        [bezier4Path curveToPoint: NSMakePoint(137.72, 148.67) controlPoint1: NSMakePoint(136.79, 148.67) controlPoint2: NSMakePoint(137.22, 148.67)];
        [bezier4Path curveToPoint: NSMakePoint(139.75, 148.67) controlPoint1: NSMakePoint(138.31, 148.67) controlPoint2: NSMakePoint(139, 148.67)];
        [bezier4Path lineToPoint: NSMakePoint(139.76, 148.46)];
        [bezier4Path curveToPoint: NSMakePoint(152.2, 136.01) controlPoint1: NSMakePoint(140.31, 141.84) controlPoint2: NSMakePoint(145.59, 136.57)];
        [bezier4Path lineToPoint: NSMakePoint(152.42, 136)];
        [bezier4Path curveToPoint: NSMakePoint(152.42, 132.7) controlPoint1: NSMakePoint(152.42, 134.58) controlPoint2: NSMakePoint(152.42, 133.44)];
        [bezier4Path curveToPoint: NSMakePoint(151.61, 132.76) controlPoint1: NSMakePoint(152.15, 132.71) controlPoint2: NSMakePoint(151.87, 132.73)];
        [bezier4Path curveToPoint: NSMakePoint(136.96, 145.34) controlPoint1: NSMakePoint(144.51, 133.49) controlPoint2: NSMakePoint(138.71, 138.6)];
        [bezier4Path curveToPoint: NSMakePoint(136.45, 148.67) controlPoint1: NSMakePoint(136.68, 146.41) controlPoint2: NSMakePoint(136.51, 147.52)];
        [bezier4Path closePath];
        [led3Color setFill];
        [bezier4Path fill];
    }


    //// X Drawing
    NSBezierPath* xPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(205, 142, 21, 21)];
    [xColor setFill];
    [xPath fill];
    [xStroke setStroke];
    [xPath setLineWidth: 2];
    [xPath stroke];


    //// Text Drawing
    NSBezierPath* textPath = NSBezierPath.bezierPath;
    [textPath moveToPoint: NSMakePoint(210, 157.87)];
    [textPath lineToPoint: NSMakePoint(213.65, 157.87)];
    [textPath lineToPoint: NSMakePoint(215.56, 154.57)];
    [textPath lineToPoint: NSMakePoint(217.4, 157.87)];
    [textPath lineToPoint: NSMakePoint(221.02, 157.87)];
    [textPath lineToPoint: NSMakePoint(217.68, 152.67)];
    [textPath lineToPoint: NSMakePoint(221.34, 147.13)];
    [textPath lineToPoint: NSMakePoint(217.61, 147.13)];
    [textPath lineToPoint: NSMakePoint(215.49, 150.58)];
    [textPath lineToPoint: NSMakePoint(213.37, 147.13)];
    [textPath lineToPoint: NSMakePoint(209.66, 147.13)];
    [textPath lineToPoint: NSMakePoint(213.37, 152.73)];
    [textPath lineToPoint: NSMakePoint(210, 157.87)];
    [textPath closePath];
    [xStroke setFill];
    [textPath fill];


    //// B Drawing
    NSBezierPath* bPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(250, 142, 21, 21)];
    [bColor setFill];
    [bPath fill];
    [bStroke setStroke];
    [bPath setLineWidth: 2];
    [bPath stroke];


    //// Text 3 Drawing
    NSBezierPath* text3Path = NSBezierPath.bezierPath;
    [text3Path moveToPoint: NSMakePoint(256.7, 157.15)];
    [text3Path lineToPoint: NSMakePoint(262.08, 157.15)];
    [text3Path curveToPoint: NSMakePoint(264.15, 156.49) controlPoint1: NSMakePoint(262.98, 157.15) controlPoint2: NSMakePoint(263.67, 156.93)];
    [text3Path curveToPoint: NSMakePoint(264.87, 154.84) controlPoint1: NSMakePoint(264.63, 156.04) controlPoint2: NSMakePoint(264.87, 155.49)];
    [text3Path curveToPoint: NSMakePoint(264.35, 153.42) controlPoint1: NSMakePoint(264.87, 154.29) controlPoint2: NSMakePoint(264.7, 153.81)];
    [text3Path curveToPoint: NSMakePoint(263.35, 152.8) controlPoint1: NSMakePoint(264.13, 153.16) controlPoint2: NSMakePoint(263.79, 152.95)];
    [text3Path curveToPoint: NSMakePoint(264.83, 151.97) controlPoint1: NSMakePoint(264.02, 152.64) controlPoint2: NSMakePoint(264.51, 152.36)];
    [text3Path curveToPoint: NSMakePoint(265.3, 150.49) controlPoint1: NSMakePoint(265.14, 151.58) controlPoint2: NSMakePoint(265.3, 151.09)];
    [text3Path curveToPoint: NSMakePoint(264.96, 149.19) controlPoint1: NSMakePoint(265.3, 150.01) controlPoint2: NSMakePoint(265.19, 149.58)];
    [text3Path curveToPoint: NSMakePoint(264.04, 148.28) controlPoint1: NSMakePoint(264.74, 148.81) controlPoint2: NSMakePoint(264.43, 148.5)];
    [text3Path curveToPoint: NSMakePoint(262.95, 147.97) controlPoint1: NSMakePoint(263.8, 148.14) controlPoint2: NSMakePoint(263.44, 148.04)];
    [text3Path curveToPoint: NSMakePoint(261.66, 147.85) controlPoint1: NSMakePoint(262.3, 147.89) controlPoint2: NSMakePoint(261.87, 147.85)];
    [text3Path lineToPoint: NSMakePoint(256.7, 147.85)];
    [text3Path lineToPoint: NSMakePoint(256.7, 157.15)];
    [text3Path closePath];
    [text3Path moveToPoint: NSMakePoint(259.6, 153.5)];
    [text3Path lineToPoint: NSMakePoint(260.85, 153.5)];
    [text3Path curveToPoint: NSMakePoint(261.79, 153.73) controlPoint1: NSMakePoint(261.3, 153.5) controlPoint2: NSMakePoint(261.61, 153.58)];
    [text3Path curveToPoint: NSMakePoint(262.05, 154.4) controlPoint1: NSMakePoint(261.96, 153.89) controlPoint2: NSMakePoint(262.05, 154.11)];
    [text3Path curveToPoint: NSMakePoint(261.79, 155.04) controlPoint1: NSMakePoint(262.05, 154.68) controlPoint2: NSMakePoint(261.96, 154.89)];
    [text3Path curveToPoint: NSMakePoint(260.87, 155.27) controlPoint1: NSMakePoint(261.61, 155.19) controlPoint2: NSMakePoint(261.31, 155.27)];
    [text3Path lineToPoint: NSMakePoint(259.6, 155.27)];
    [text3Path lineToPoint: NSMakePoint(259.6, 153.5)];
    [text3Path closePath];
    [text3Path moveToPoint: NSMakePoint(259.6, 149.85)];
    [text3Path lineToPoint: NSMakePoint(261.07, 149.85)];
    [text3Path curveToPoint: NSMakePoint(262.11, 150.11) controlPoint1: NSMakePoint(261.56, 149.85) controlPoint2: NSMakePoint(261.91, 149.93)];
    [text3Path curveToPoint: NSMakePoint(262.42, 150.82) controlPoint1: NSMakePoint(262.32, 150.29) controlPoint2: NSMakePoint(262.42, 150.52)];
    [text3Path curveToPoint: NSMakePoint(262.12, 151.48) controlPoint1: NSMakePoint(262.42, 151.09) controlPoint2: NSMakePoint(262.32, 151.31)];
    [text3Path curveToPoint: NSMakePoint(261.06, 151.73) controlPoint1: NSMakePoint(261.92, 151.65) controlPoint2: NSMakePoint(261.56, 151.73)];
    [text3Path lineToPoint: NSMakePoint(259.6, 151.73)];
    [text3Path lineToPoint: NSMakePoint(259.6, 149.85)];
    [text3Path closePath];
    [bStroke setFill];
    [text3Path fill];


    //// Y Drawing
    NSBezierPath* yPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(228, 165, 21, 21)];
    [yColor setFill];
    [yPath fill];
    [yStroke setStroke];
    [yPath setLineWidth: 2];
    [yPath stroke];


    //// Text 4 Drawing
    NSBezierPath* text4Path = NSBezierPath.bezierPath;
    [text4Path moveToPoint: NSMakePoint(233.44, 180.15)];
    [text4Path lineToPoint: NSMakePoint(236.63, 180.15)];
    [text4Path lineToPoint: NSMakePoint(238.51, 177.01)];
    [text4Path lineToPoint: NSMakePoint(240.39, 180.15)];
    [text4Path lineToPoint: NSMakePoint(243.57, 180.15)];
    [text4Path lineToPoint: NSMakePoint(239.95, 174.74)];
    [text4Path lineToPoint: NSMakePoint(239.95, 170.85)];
    [text4Path lineToPoint: NSMakePoint(237.07, 170.85)];
    [text4Path lineToPoint: NSMakePoint(237.07, 174.74)];
    [text4Path lineToPoint: NSMakePoint(233.44, 180.15)];
    [text4Path closePath];
    [yStroke setFill];
    [text4Path fill];


    //// A Drawing
    NSBezierPath* aPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(228, 119, 21, 21)];
    [aColor setFill];
    [aPath fill];
    [aStroke setStroke];
    [aPath setLineWidth: 2];
    [aPath stroke];


    //// Text 2 Drawing
    NSBezierPath* text2Path = NSBezierPath.bezierPath;
    [text2Path moveToPoint: NSMakePoint(240.1, 126.38)];
    [text2Path lineToPoint: NSMakePoint(236.82, 126.38)];
    [text2Path lineToPoint: NSMakePoint(236.37, 124.85)];
    [text2Path lineToPoint: NSMakePoint(233.43, 124.85)];
    [text2Path lineToPoint: NSMakePoint(236.93, 134.15)];
    [text2Path lineToPoint: NSMakePoint(240.07, 134.15)];
    [text2Path lineToPoint: NSMakePoint(243.57, 124.85)];
    [text2Path lineToPoint: NSMakePoint(240.56, 124.85)];
    [text2Path lineToPoint: NSMakePoint(240.1, 126.38)];
    [text2Path closePath];
    [text2Path moveToPoint: NSMakePoint(239.5, 128.4)];
    [text2Path lineToPoint: NSMakePoint(238.47, 131.74)];
    [text2Path lineToPoint: NSMakePoint(237.45, 128.4)];
    [text2Path lineToPoint: NSMakePoint(239.5, 128.4)];
    [text2Path closePath];
    [aStroke setFill];
    [text2Path fill];


    //// Group 6
    {
        //// Oval 3 Drawing
        NSBezierPath* oval3Path = NSBezierPath.bezierPath;
        [oval3Path moveToPoint: NSMakePoint(135, 102.5)];
        [oval3Path curveToPoint: NSMakePoint(109.5, 128) controlPoint1: NSMakePoint(135, 116.58) controlPoint2: NSMakePoint(123.58, 128)];
        [oval3Path curveToPoint: NSMakePoint(84, 102.5) controlPoint1: NSMakePoint(95.42, 128) controlPoint2: NSMakePoint(84, 116.58)];
        [oval3Path curveToPoint: NSMakePoint(109.5, 77) controlPoint1: NSMakePoint(84, 88.42) controlPoint2: NSMakePoint(95.42, 77)];
        [oval3Path curveToPoint: NSMakePoint(135, 102.5) controlPoint1: NSMakePoint(123.58, 77) controlPoint2: NSMakePoint(135, 88.42)];
        [oval3Path closePath];
        [darkController setFill];
        [oval3Path fill];


        //// Oval 5 Drawing
        NSBezierPath* oval5Path = NSBezierPath.bezierPath;
        [oval5Path moveToPoint: NSMakePoint(133, 102.5)];
        [oval5Path curveToPoint: NSMakePoint(109.5, 126) controlPoint1: NSMakePoint(133, 115.48) controlPoint2: NSMakePoint(122.48, 126)];
        [oval5Path curveToPoint: NSMakePoint(86, 102.5) controlPoint1: NSMakePoint(96.52, 126) controlPoint2: NSMakePoint(86, 115.48)];
        [oval5Path curveToPoint: NSMakePoint(109.5, 79) controlPoint1: NSMakePoint(86, 89.52) controlPoint2: NSMakePoint(96.52, 79)];
        [oval5Path curveToPoint: NSMakePoint(133, 102.5) controlPoint1: NSMakePoint(122.48, 79) controlPoint2: NSMakePoint(133, 89.52)];
        [oval5Path closePath];
        [cross setFill];
        [oval5Path fill];
        [crossStroke setStroke];
        [oval5Path setLineWidth: 1];
        [oval5Path stroke];


        //// Bezier 5 Drawing
        NSBezierPath* bezier5Path = NSBezierPath.bezierPath;
        [bezier5Path moveToPoint: NSMakePoint(116.84, 124.83)];
        [bezier5Path curveToPoint: NSMakePoint(117.47, 117.19) controlPoint1: NSMakePoint(116.87, 123.75) controlPoint2: NSMakePoint(117, 120.16)];
        [bezier5Path curveToPoint: NSMakePoint(123.15, 110.43) controlPoint1: NSMakePoint(118.04, 113.65) controlPoint2: NSMakePoint(120.67, 111.25)];
        [bezier5Path curveToPoint: NSMakePoint(131.85, 109.77) controlPoint1: NSMakePoint(125.34, 109.71) controlPoint2: NSMakePoint(130.6, 109.75)];
        [bezier5Path curveToPoint: NSMakePoint(133, 102.5) controlPoint1: NSMakePoint(132.6, 107.48) controlPoint2: NSMakePoint(133, 105.04)];
        [bezier5Path curveToPoint: NSMakePoint(131.8, 95.06) controlPoint1: NSMakePoint(133, 99.9) controlPoint2: NSMakePoint(132.58, 97.4)];
        [bezier5Path curveToPoint: NSMakePoint(124.09, 94.42) controlPoint1: NSMakePoint(130.81, 95.03) controlPoint2: NSMakePoint(127.12, 94.91)];
        [bezier5Path curveToPoint: NSMakePoint(117.32, 88.74) controlPoint1: NSMakePoint(120.55, 93.85) controlPoint2: NSMakePoint(118.15, 91.23)];
        [bezier5Path curveToPoint: NSMakePoint(116.66, 80.11) controlPoint1: NSMakePoint(116.61, 86.6) controlPoint2: NSMakePoint(116.64, 81.48)];
        [bezier5Path curveToPoint: NSMakePoint(109.5, 79) controlPoint1: NSMakePoint(114.41, 79.39) controlPoint2: NSMakePoint(112, 79)];
        [bezier5Path curveToPoint: NSMakePoint(104.31, 79.57) controlPoint1: NSMakePoint(107.72, 79) controlPoint2: NSMakePoint(105.98, 79.2)];
        [bezier5Path curveToPoint: NSMakePoint(101.95, 80.24) controlPoint1: NSMakePoint(103.51, 79.76) controlPoint2: NSMakePoint(102.72, 79.98)];
        [bezier5Path curveToPoint: NSMakePoint(101.32, 87.81) controlPoint1: NSMakePoint(101.92, 81.4) controlPoint2: NSMakePoint(101.78, 84.9)];
        [bezier5Path curveToPoint: NSMakePoint(95.64, 94.57) controlPoint1: NSMakePoint(100.75, 91.35) controlPoint2: NSMakePoint(98.13, 93.75)];
        [bezier5Path curveToPoint: NSMakePoint(89.96, 95.21) controlPoint1: NSMakePoint(94.34, 95) controlPoint2: NSMakePoint(91.95, 95.16)];
        [bezier5Path curveToPoint: NSMakePoint(87.14, 95.23) controlPoint1: NSMakePoint(88.77, 95.25) controlPoint2: NSMakePoint(87.72, 95.24)];
        [bezier5Path curveToPoint: NSMakePoint(86, 102.5) controlPoint1: NSMakePoint(86.4, 97.52) controlPoint2: NSMakePoint(86, 99.96)];
        [bezier5Path curveToPoint: NSMakePoint(87.2, 109.95) controlPoint1: NSMakePoint(86, 105.1) controlPoint2: NSMakePoint(86.42, 107.61)];
        [bezier5Path curveToPoint: NSMakePoint(89.98, 110.08) controlPoint1: NSMakePoint(87.76, 109.96) controlPoint2: NSMakePoint(88.78, 110)];
        [bezier5Path curveToPoint: NSMakePoint(94.7, 110.58) controlPoint1: NSMakePoint(91.43, 110.17) controlPoint2: NSMakePoint(93.15, 110.33)];
        [bezier5Path curveToPoint: NSMakePoint(101.47, 116.26) controlPoint1: NSMakePoint(98.24, 111.15) controlPoint2: NSMakePoint(100.64, 113.77)];
        [bezier5Path curveToPoint: NSMakePoint(102.13, 124.82) controlPoint1: NSMakePoint(102.17, 118.37) controlPoint2: NSMakePoint(102.15, 123.36)];
        [bezier5Path curveToPoint: NSMakePoint(109.5, 126) controlPoint1: NSMakePoint(104.45, 125.59) controlPoint2: NSMakePoint(106.93, 126)];
        [bezier5Path curveToPoint: NSMakePoint(116.84, 124.83) controlPoint1: NSMakePoint(112.06, 126) controlPoint2: NSMakePoint(114.53, 125.59)];
        [bezier5Path closePath];
        [cross setFill];
        [bezier5Path fill];
        [crossStroke setStroke];
        [bezier5Path setLineWidth: 1];
        [bezier5Path stroke];


        //// Left
        {
            //// Bezier 11 Drawing
            NSBezierPath* bezier11Path = NSBezierPath.bezierPath;
            [bezier11Path moveToPoint: NSMakePoint(99.2, 92.2)];
            [bezier11Path curveToPoint: NSMakePoint(95.64, 94.57) controlPoint1: NSMakePoint(98.16, 93.35) controlPoint2: NSMakePoint(96.88, 94.16)];
            [bezier11Path curveToPoint: NSMakePoint(93.29, 95.01) controlPoint1: NSMakePoint(95.04, 94.77) controlPoint2: NSMakePoint(94.21, 94.91)];
            [bezier11Path curveToPoint: NSMakePoint(89.96, 95.21) controlPoint1: NSMakePoint(92.22, 95.13) controlPoint2: NSMakePoint(91.04, 95.19)];
            [bezier11Path curveToPoint: NSMakePoint(87.14, 95.23) controlPoint1: NSMakePoint(88.77, 95.25) controlPoint2: NSMakePoint(87.72, 95.24)];
            [bezier11Path curveToPoint: NSMakePoint(86, 102.5) controlPoint1: NSMakePoint(86.4, 97.52) controlPoint2: NSMakePoint(86, 99.96)];
            [bezier11Path curveToPoint: NSMakePoint(87.2, 109.95) controlPoint1: NSMakePoint(86, 105.1) controlPoint2: NSMakePoint(86.42, 107.61)];
            [bezier11Path curveToPoint: NSMakePoint(89.98, 110.08) controlPoint1: NSMakePoint(87.76, 109.96) controlPoint2: NSMakePoint(88.78, 110)];
            [bezier11Path curveToPoint: NSMakePoint(94.7, 110.58) controlPoint1: NSMakePoint(91.43, 110.17) controlPoint2: NSMakePoint(93.15, 110.33)];
            [bezier11Path curveToPoint: NSMakePoint(99.21, 112.79) controlPoint1: NSMakePoint(96.53, 110.87) controlPoint2: NSMakePoint(98.05, 111.71)];
            [bezier11Path curveToPoint: NSMakePoint(109.5, 102.5) controlPoint1: NSMakePoint(104.63, 107.37) controlPoint2: NSMakePoint(109.5, 102.5)];
            [bezier11Path curveToPoint: NSMakePoint(99.2, 92.2) controlPoint1: NSMakePoint(109.5, 102.5) controlPoint2: NSMakePoint(104.63, 97.63)];
            [bezier11Path closePath];
            [leftColor setFill];
            [bezier11Path fill];


            //// Bezier 7 Drawing
            NSBezierPath* bezier7Path = NSBezierPath.bezierPath;
            [bezier7Path moveToPoint: NSMakePoint(99.2, 92.2)];
            [bezier7Path curveToPoint: NSMakePoint(95.64, 94.57) controlPoint1: NSMakePoint(98.16, 93.35) controlPoint2: NSMakePoint(96.88, 94.16)];
            [bezier7Path curveToPoint: NSMakePoint(93.29, 95.01) controlPoint1: NSMakePoint(95.04, 94.77) controlPoint2: NSMakePoint(94.21, 94.91)];
            [bezier7Path curveToPoint: NSMakePoint(89.96, 95.21) controlPoint1: NSMakePoint(92.22, 95.13) controlPoint2: NSMakePoint(91.04, 95.19)];
            [bezier7Path curveToPoint: NSMakePoint(87.14, 95.23) controlPoint1: NSMakePoint(88.77, 95.25) controlPoint2: NSMakePoint(87.72, 95.24)];
            [bezier7Path curveToPoint: NSMakePoint(86, 102.5) controlPoint1: NSMakePoint(86.4, 97.52) controlPoint2: NSMakePoint(86, 99.96)];
            [bezier7Path curveToPoint: NSMakePoint(87.2, 109.95) controlPoint1: NSMakePoint(86, 105.1) controlPoint2: NSMakePoint(86.42, 107.61)];
            [bezier7Path curveToPoint: NSMakePoint(89.98, 110.08) controlPoint1: NSMakePoint(87.76, 109.96) controlPoint2: NSMakePoint(88.78, 110)];
            [bezier7Path curveToPoint: NSMakePoint(94.7, 110.58) controlPoint1: NSMakePoint(91.43, 110.17) controlPoint2: NSMakePoint(93.15, 110.33)];
            [bezier7Path curveToPoint: NSMakePoint(99.21, 112.79) controlPoint1: NSMakePoint(96.53, 110.87) controlPoint2: NSMakePoint(98.05, 111.71)];
            [leftStroke setStroke];
            [bezier7Path setLineWidth: 1];
            [bezier7Path stroke];
        }


        //// up
        {
            //// Bezier 10 Drawing
            NSBezierPath* bezier10Path = NSBezierPath.bezierPath;
            [bezier10Path moveToPoint: NSMakePoint(116.84, 124.83)];
            [bezier10Path curveToPoint: NSMakePoint(117.47, 117.19) controlPoint1: NSMakePoint(116.87, 123.75) controlPoint2: NSMakePoint(117, 120.16)];
            [bezier10Path curveToPoint: NSMakePoint(119.69, 112.69) controlPoint1: NSMakePoint(117.77, 115.37) controlPoint2: NSMakePoint(118.6, 113.85)];
            [bezier10Path curveToPoint: NSMakePoint(109.5, 102.5) controlPoint1: NSMakePoint(114.31, 107.31) controlPoint2: NSMakePoint(109.5, 102.5)];
            [bezier10Path curveToPoint: NSMakePoint(99.21, 112.79) controlPoint1: NSMakePoint(109.5, 102.5) controlPoint2: NSMakePoint(104.63, 107.37)];
            [bezier10Path curveToPoint: NSMakePoint(101.47, 116.26) controlPoint1: NSMakePoint(100.3, 113.81) controlPoint2: NSMakePoint(101.07, 115.05)];
            [bezier10Path curveToPoint: NSMakePoint(102.13, 124.82) controlPoint1: NSMakePoint(102.17, 118.37) controlPoint2: NSMakePoint(102.15, 123.36)];
            [bezier10Path curveToPoint: NSMakePoint(109.5, 126) controlPoint1: NSMakePoint(104.45, 125.59) controlPoint2: NSMakePoint(106.93, 126)];
            [bezier10Path curveToPoint: NSMakePoint(116.84, 124.83) controlPoint1: NSMakePoint(112.06, 126) controlPoint2: NSMakePoint(114.53, 125.59)];
            [bezier10Path closePath];
            [upColor setFill];
            [bezier10Path fill];


            //// Bezier 12 Drawing
            NSBezierPath* bezier12Path = NSBezierPath.bezierPath;
            [bezier12Path moveToPoint: NSMakePoint(99.21, 112.79)];
            [bezier12Path curveToPoint: NSMakePoint(101.47, 116.26) controlPoint1: NSMakePoint(100.3, 113.81) controlPoint2: NSMakePoint(101.07, 115.05)];
            [bezier12Path curveToPoint: NSMakePoint(102.13, 124.82) controlPoint1: NSMakePoint(102.17, 118.37) controlPoint2: NSMakePoint(102.15, 123.36)];
            [bezier12Path curveToPoint: NSMakePoint(109.5, 126) controlPoint1: NSMakePoint(104.45, 125.59) controlPoint2: NSMakePoint(106.93, 126)];
            [bezier12Path curveToPoint: NSMakePoint(116.84, 124.83) controlPoint1: NSMakePoint(112.06, 126) controlPoint2: NSMakePoint(114.53, 125.59)];
            [bezier12Path curveToPoint: NSMakePoint(117.47, 117.19) controlPoint1: NSMakePoint(116.87, 123.75) controlPoint2: NSMakePoint(117, 120.16)];
            [bezier12Path curveToPoint: NSMakePoint(119.69, 112.69) controlPoint1: NSMakePoint(117.77, 115.37) controlPoint2: NSMakePoint(118.6, 113.85)];
            [upStroke setStroke];
            [bezier12Path setLineWidth: 1];
            [bezier12Path stroke];
        }


        //// Right
        {
            //// Bezier 9 Drawing
            NSBezierPath* bezier9Path = NSBezierPath.bezierPath;
            [bezier9Path moveToPoint: NSMakePoint(123.15, 110.43)];
            [bezier9Path curveToPoint: NSMakePoint(131.85, 109.77) controlPoint1: NSMakePoint(125.34, 109.71) controlPoint2: NSMakePoint(130.6, 109.75)];
            [bezier9Path curveToPoint: NSMakePoint(133, 102.5) controlPoint1: NSMakePoint(132.6, 107.48) controlPoint2: NSMakePoint(133, 105.04)];
            [bezier9Path curveToPoint: NSMakePoint(131.8, 95.06) controlPoint1: NSMakePoint(133, 99.9) controlPoint2: NSMakePoint(132.58, 97.4)];
            [bezier9Path curveToPoint: NSMakePoint(124.09, 94.42) controlPoint1: NSMakePoint(130.81, 95.03) controlPoint2: NSMakePoint(127.12, 94.91)];
            [bezier9Path curveToPoint: NSMakePoint(119.69, 92.31) controlPoint1: NSMakePoint(122.32, 94.14) controlPoint2: NSMakePoint(120.84, 93.34)];
            [bezier9Path curveToPoint: NSMakePoint(114.27, 97.73) controlPoint1: NSMakePoint(117.74, 94.26) controlPoint2: NSMakePoint(115.87, 96.13)];
            [bezier9Path curveToPoint: NSMakePoint(109.5, 102.5) controlPoint1: NSMakePoint(111.46, 100.54) controlPoint2: NSMakePoint(109.5, 102.5)];
            [bezier9Path curveToPoint: NSMakePoint(119.69, 112.69) controlPoint1: NSMakePoint(109.5, 102.5) controlPoint2: NSMakePoint(114.31, 107.31)];
            [bezier9Path curveToPoint: NSMakePoint(123.15, 110.43) controlPoint1: NSMakePoint(120.71, 111.6) controlPoint2: NSMakePoint(121.95, 110.83)];
            [bezier9Path closePath];
            [rightColor setFill];
            [bezier9Path fill];


            //// Bezier 13 Drawing
            NSBezierPath* bezier13Path = NSBezierPath.bezierPath;
            [bezier13Path moveToPoint: NSMakePoint(119.69, 112.69)];
            [bezier13Path curveToPoint: NSMakePoint(123.15, 110.43) controlPoint1: NSMakePoint(120.71, 111.6) controlPoint2: NSMakePoint(121.95, 110.83)];
            [bezier13Path curveToPoint: NSMakePoint(131.85, 109.77) controlPoint1: NSMakePoint(125.34, 109.71) controlPoint2: NSMakePoint(130.6, 109.75)];
            [bezier13Path curveToPoint: NSMakePoint(133, 102.5) controlPoint1: NSMakePoint(132.6, 107.48) controlPoint2: NSMakePoint(133, 105.04)];
            [bezier13Path curveToPoint: NSMakePoint(131.8, 95.06) controlPoint1: NSMakePoint(133, 99.9) controlPoint2: NSMakePoint(132.58, 97.4)];
            [bezier13Path curveToPoint: NSMakePoint(124.09, 94.42) controlPoint1: NSMakePoint(130.81, 95.03) controlPoint2: NSMakePoint(127.12, 94.91)];
            [bezier13Path curveToPoint: NSMakePoint(119.69, 92.31) controlPoint1: NSMakePoint(122.32, 94.14) controlPoint2: NSMakePoint(120.84, 93.34)];
            [rightStroke setStroke];
            [bezier13Path setLineWidth: 1];
            [bezier13Path stroke];
        }


        //// Down
        {
            //// Bezier 8 Drawing
            NSBezierPath* bezier8Path = NSBezierPath.bezierPath;
            [bezier8Path moveToPoint: NSMakePoint(109.5, 102.5)];
            [bezier8Path curveToPoint: NSMakePoint(119.69, 92.31) controlPoint1: NSMakePoint(109.5, 102.5) controlPoint2: NSMakePoint(114.31, 97.69)];
            [bezier8Path curveToPoint: NSMakePoint(117.32, 88.74) controlPoint1: NSMakePoint(118.54, 91.27) controlPoint2: NSMakePoint(117.74, 89.99)];
            [bezier8Path curveToPoint: NSMakePoint(116.66, 80.11) controlPoint1: NSMakePoint(116.61, 86.6) controlPoint2: NSMakePoint(116.64, 81.48)];
            [bezier8Path curveToPoint: NSMakePoint(109.5, 79) controlPoint1: NSMakePoint(114.41, 79.39) controlPoint2: NSMakePoint(112, 79)];
            [bezier8Path curveToPoint: NSMakePoint(104.31, 79.57) controlPoint1: NSMakePoint(107.72, 79) controlPoint2: NSMakePoint(105.98, 79.2)];
            [bezier8Path curveToPoint: NSMakePoint(101.95, 80.24) controlPoint1: NSMakePoint(103.51, 79.76) controlPoint2: NSMakePoint(102.72, 79.98)];
            [bezier8Path curveToPoint: NSMakePoint(101.32, 87.81) controlPoint1: NSMakePoint(101.92, 81.4) controlPoint2: NSMakePoint(101.78, 84.9)];
            [bezier8Path curveToPoint: NSMakePoint(100.8, 89.68) controlPoint1: NSMakePoint(101.21, 88.47) controlPoint2: NSMakePoint(101.03, 89.1)];
            [bezier8Path curveToPoint: NSMakePoint(99.2, 92.2) controlPoint1: NSMakePoint(100.4, 90.64) controlPoint2: NSMakePoint(99.85, 91.49)];
            [bezier8Path curveToPoint: NSMakePoint(109.5, 102.5) controlPoint1: NSMakePoint(104.63, 97.63) controlPoint2: NSMakePoint(109.5, 102.5)];
            [bezier8Path closePath];
            [downColor setFill];
            [bezier8Path fill];


            //// Bezier 14 Drawing
            NSBezierPath* bezier14Path = NSBezierPath.bezierPath;
            [bezier14Path moveToPoint: NSMakePoint(119.69, 92.31)];
            [bezier14Path curveToPoint: NSMakePoint(117.32, 88.74) controlPoint1: NSMakePoint(118.54, 91.27) controlPoint2: NSMakePoint(117.74, 89.99)];
            [bezier14Path curveToPoint: NSMakePoint(116.66, 80.11) controlPoint1: NSMakePoint(116.61, 86.6) controlPoint2: NSMakePoint(116.64, 81.48)];
            [bezier14Path curveToPoint: NSMakePoint(109.5, 79) controlPoint1: NSMakePoint(114.41, 79.39) controlPoint2: NSMakePoint(112, 79)];
            [bezier14Path curveToPoint: NSMakePoint(104.31, 79.57) controlPoint1: NSMakePoint(107.72, 79) controlPoint2: NSMakePoint(105.98, 79.2)];
            [bezier14Path curveToPoint: NSMakePoint(101.95, 80.24) controlPoint1: NSMakePoint(103.51, 79.76) controlPoint2: NSMakePoint(102.72, 79.98)];
            [bezier14Path curveToPoint: NSMakePoint(101.32, 87.81) controlPoint1: NSMakePoint(101.92, 81.4) controlPoint2: NSMakePoint(101.78, 84.9)];
            [bezier14Path curveToPoint: NSMakePoint(100.8, 89.68) controlPoint1: NSMakePoint(101.21, 88.47) controlPoint2: NSMakePoint(101.03, 89.1)];
            [bezier14Path curveToPoint: NSMakePoint(99.2, 92.2) controlPoint1: NSMakePoint(100.4, 90.64) controlPoint2: NSMakePoint(99.85, 91.49)];
            [downStroke setStroke];
            [bezier14Path setLineWidth: 1];
            [bezier14Path stroke];
        }
    }


    //// stick Left
    {
        //// Oval 6 Drawing
        NSBezierPath* oval6Path = NSBezierPath.bezierPath;
        [oval6Path moveToPoint: NSMakePoint(90, 155)];
        [oval6Path curveToPoint: NSMakePoint(69, 176) controlPoint1: NSMakePoint(90, 166.6) controlPoint2: NSMakePoint(80.6, 176)];
        [oval6Path curveToPoint: NSMakePoint(48, 155) controlPoint1: NSMakePoint(57.4, 176) controlPoint2: NSMakePoint(48, 166.6)];
        [oval6Path curveToPoint: NSMakePoint(69, 134) controlPoint1: NSMakePoint(48, 143.4) controlPoint2: NSMakePoint(57.4, 134)];
        [oval6Path curveToPoint: NSMakePoint(90, 155) controlPoint1: NSMakePoint(80.6, 134) controlPoint2: NSMakePoint(90, 143.4)];
        [oval6Path closePath];
        [highlightStick setFill];
        [oval6Path fill];
        [darkController setStroke];
        [oval6Path setLineWidth: 2];
        [oval6Path stroke];


        //// knobLeft
        {
            [NSGraphicsContext saveGraphicsState];
            CGContextTranslateCTM(context, leftStickPosition.x, leftStickPosition.y);
            CGContextScaleCTM(context, leftXScale, leftYScale);



            //// Oval 7 Drawing
            NSBezierPath* oval7Path = NSBezierPath.bezierPath;
            [oval7Path moveToPoint: NSMakePoint(20, 0)];
            [oval7Path curveToPoint: NSMakePoint(0, 20) controlPoint1: NSMakePoint(20, 11.05) controlPoint2: NSMakePoint(11.05, 20)];
            [oval7Path curveToPoint: NSMakePoint(-20, 0) controlPoint1: NSMakePoint(-11.05, 20) controlPoint2: NSMakePoint(-20, 11.05)];
            [oval7Path curveToPoint: NSMakePoint(0, -20) controlPoint1: NSMakePoint(-20, -11.05) controlPoint2: NSMakePoint(-11.05, -20)];
            [oval7Path curveToPoint: NSMakePoint(20, 0) controlPoint1: NSMakePoint(11.05, -20) controlPoint2: NSMakePoint(20, -11.05)];
            [oval7Path closePath];
            [leftStickColor setFill];
            [oval7Path fill];
            [leftStickStroke setStroke];
            [oval7Path setLineWidth: 2];
            [oval7Path stroke];


            //// Oval 10 Drawing
            NSBezierPath* oval10Path = NSBezierPath.bezierPath;
            [oval10Path moveToPoint: NSMakePoint(1, 12)];
            [oval10Path curveToPoint: NSMakePoint(0, 13) controlPoint1: NSMakePoint(1, 12.55) controlPoint2: NSMakePoint(0.55, 13)];
            [oval10Path curveToPoint: NSMakePoint(-1, 12) controlPoint1: NSMakePoint(-0.55, 13) controlPoint2: NSMakePoint(-1, 12.55)];
            [oval10Path curveToPoint: NSMakePoint(0, 11) controlPoint1: NSMakePoint(-1, 11.45) controlPoint2: NSMakePoint(-0.55, 11)];
            [oval10Path curveToPoint: NSMakePoint(1, 12) controlPoint1: NSMakePoint(0.55, 11) controlPoint2: NSMakePoint(1, 11.45)];
            [oval10Path closePath];
            [NSColor.grayColor setFill];
            [oval10Path fill];


            //// Oval 11 Drawing
            NSBezierPath* oval11Path = NSBezierPath.bezierPath;
            [oval11Path moveToPoint: NSMakePoint(-11, 0)];
            [oval11Path curveToPoint: NSMakePoint(-12, 1) controlPoint1: NSMakePoint(-11, 0.55) controlPoint2: NSMakePoint(-11.45, 1)];
            [oval11Path curveToPoint: NSMakePoint(-13, 0) controlPoint1: NSMakePoint(-12.55, 1) controlPoint2: NSMakePoint(-13, 0.55)];
            [oval11Path curveToPoint: NSMakePoint(-12, -1) controlPoint1: NSMakePoint(-13, -0.55) controlPoint2: NSMakePoint(-12.55, -1)];
            [oval11Path curveToPoint: NSMakePoint(-11, 0) controlPoint1: NSMakePoint(-11.45, -1) controlPoint2: NSMakePoint(-11, -0.55)];
            [oval11Path closePath];
            [NSColor.grayColor setFill];
            [oval11Path fill];


            //// Oval 12 Drawing
            NSBezierPath* oval12Path = NSBezierPath.bezierPath;
            [oval12Path moveToPoint: NSMakePoint(13, 0)];
            [oval12Path curveToPoint: NSMakePoint(12, 1) controlPoint1: NSMakePoint(13, 0.55) controlPoint2: NSMakePoint(12.55, 1)];
            [oval12Path curveToPoint: NSMakePoint(11, 0) controlPoint1: NSMakePoint(11.45, 1) controlPoint2: NSMakePoint(11, 0.55)];
            [oval12Path curveToPoint: NSMakePoint(12, -1) controlPoint1: NSMakePoint(11, -0.55) controlPoint2: NSMakePoint(11.45, -1)];
            [oval12Path curveToPoint: NSMakePoint(13, 0) controlPoint1: NSMakePoint(12.55, -1) controlPoint2: NSMakePoint(13, -0.55)];
            [oval12Path closePath];
            [NSColor.grayColor setFill];
            [oval12Path fill];


            //// Oval 13 Drawing
            NSBezierPath* oval13Path = NSBezierPath.bezierPath;
            [oval13Path moveToPoint: NSMakePoint(1, -12)];
            [oval13Path curveToPoint: NSMakePoint(0, -11) controlPoint1: NSMakePoint(1, -11.45) controlPoint2: NSMakePoint(0.55, -11)];
            [oval13Path curveToPoint: NSMakePoint(-1, -12) controlPoint1: NSMakePoint(-0.55, -11) controlPoint2: NSMakePoint(-1, -11.45)];
            [oval13Path curveToPoint: NSMakePoint(0, -13) controlPoint1: NSMakePoint(-1, -12.55) controlPoint2: NSMakePoint(-0.55, -13)];
            [oval13Path curveToPoint: NSMakePoint(1, -12) controlPoint1: NSMakePoint(0.55, -13) controlPoint2: NSMakePoint(1, -12.55)];
            [oval13Path closePath];
            [NSColor.grayColor setFill];
            [oval13Path fill];



            [NSGraphicsContext restoreGraphicsState];
        }
    }


    //// stick Right
    {
        //// Oval 8 Drawing
        NSBezierPath* oval8Path = NSBezierPath.bezierPath;
        [oval8Path moveToPoint: NSMakePoint(216, 104)];
        [oval8Path curveToPoint: NSMakePoint(195, 125) controlPoint1: NSMakePoint(216, 115.6) controlPoint2: NSMakePoint(206.6, 125)];
        [oval8Path curveToPoint: NSMakePoint(174, 104) controlPoint1: NSMakePoint(183.4, 125) controlPoint2: NSMakePoint(174, 115.6)];
        [oval8Path curveToPoint: NSMakePoint(195, 83) controlPoint1: NSMakePoint(174, 92.4) controlPoint2: NSMakePoint(183.4, 83)];
        [oval8Path curveToPoint: NSMakePoint(216, 104) controlPoint1: NSMakePoint(206.6, 83) controlPoint2: NSMakePoint(216, 92.4)];
        [oval8Path closePath];
        [highlightStick setFill];
        [oval8Path fill];
        [darkController setStroke];
        [oval8Path setLineWidth: 2];
        [oval8Path stroke];


        //// knob Right
        {
            [NSGraphicsContext saveGraphicsState];
            CGContextTranslateCTM(context, rightStickPosition2.x, rightStickPosition2.y);



            //// Oval 9 Drawing
            NSBezierPath* oval9Path = NSBezierPath.bezierPath;
            [oval9Path moveToPoint: NSMakePoint(20, 0)];
            [oval9Path curveToPoint: NSMakePoint(0, 20) controlPoint1: NSMakePoint(20, 11.05) controlPoint2: NSMakePoint(11.05, 20)];
            [oval9Path curveToPoint: NSMakePoint(-20, 0) controlPoint1: NSMakePoint(-11.05, 20) controlPoint2: NSMakePoint(-20, 11.05)];
            [oval9Path curveToPoint: NSMakePoint(0, -20) controlPoint1: NSMakePoint(-20, -11.05) controlPoint2: NSMakePoint(-11.05, -20)];
            [oval9Path curveToPoint: NSMakePoint(20, 0) controlPoint1: NSMakePoint(11.05, -20) controlPoint2: NSMakePoint(20, -11.05)];
            [oval9Path closePath];
            [rightStickColor setFill];
            [oval9Path fill];
            [rightStickStroke setStroke];
            [oval9Path setLineWidth: 2];
            [oval9Path stroke];


            //// Oval 14 Drawing
            NSBezierPath* oval14Path = NSBezierPath.bezierPath;
            [oval14Path moveToPoint: NSMakePoint(1, 12)];
            [oval14Path curveToPoint: NSMakePoint(0, 13) controlPoint1: NSMakePoint(1, 12.55) controlPoint2: NSMakePoint(0.55, 13)];
            [oval14Path curveToPoint: NSMakePoint(-1, 12) controlPoint1: NSMakePoint(-0.55, 13) controlPoint2: NSMakePoint(-1, 12.55)];
            [oval14Path curveToPoint: NSMakePoint(0, 11) controlPoint1: NSMakePoint(-1, 11.45) controlPoint2: NSMakePoint(-0.55, 11)];
            [oval14Path curveToPoint: NSMakePoint(1, 12) controlPoint1: NSMakePoint(0.55, 11) controlPoint2: NSMakePoint(1, 11.45)];
            [oval14Path closePath];
            [NSColor.grayColor setFill];
            [oval14Path fill];


            //// Oval 15 Drawing
            NSBezierPath* oval15Path = NSBezierPath.bezierPath;
            [oval15Path moveToPoint: NSMakePoint(-11, 0)];
            [oval15Path curveToPoint: NSMakePoint(-12, 1) controlPoint1: NSMakePoint(-11, 0.55) controlPoint2: NSMakePoint(-11.45, 1)];
            [oval15Path curveToPoint: NSMakePoint(-13, 0) controlPoint1: NSMakePoint(-12.55, 1) controlPoint2: NSMakePoint(-13, 0.55)];
            [oval15Path curveToPoint: NSMakePoint(-12, -1) controlPoint1: NSMakePoint(-13, -0.55) controlPoint2: NSMakePoint(-12.55, -1)];
            [oval15Path curveToPoint: NSMakePoint(-11, 0) controlPoint1: NSMakePoint(-11.45, -1) controlPoint2: NSMakePoint(-11, -0.55)];
            [oval15Path closePath];
            [NSColor.grayColor setFill];
            [oval15Path fill];


            //// Oval 16 Drawing
            NSBezierPath* oval16Path = NSBezierPath.bezierPath;
            [oval16Path moveToPoint: NSMakePoint(13, 0)];
            [oval16Path curveToPoint: NSMakePoint(12, 1) controlPoint1: NSMakePoint(13, 0.55) controlPoint2: NSMakePoint(12.55, 1)];
            [oval16Path curveToPoint: NSMakePoint(11, 0) controlPoint1: NSMakePoint(11.45, 1) controlPoint2: NSMakePoint(11, 0.55)];
            [oval16Path curveToPoint: NSMakePoint(12, -1) controlPoint1: NSMakePoint(11, -0.55) controlPoint2: NSMakePoint(11.45, -1)];
            [oval16Path curveToPoint: NSMakePoint(13, 0) controlPoint1: NSMakePoint(12.55, -1) controlPoint2: NSMakePoint(13, -0.55)];
            [oval16Path closePath];
            [NSColor.grayColor setFill];
            [oval16Path fill];


            //// Oval 17 Drawing
            NSBezierPath* oval17Path = NSBezierPath.bezierPath;
            [oval17Path moveToPoint: NSMakePoint(1, -12)];
            [oval17Path curveToPoint: NSMakePoint(0, -11) controlPoint1: NSMakePoint(1, -11.45) controlPoint2: NSMakePoint(0.55, -11)];
            [oval17Path curveToPoint: NSMakePoint(-1, -12) controlPoint1: NSMakePoint(-0.55, -11) controlPoint2: NSMakePoint(-1, -11.45)];
            [oval17Path curveToPoint: NSMakePoint(0, -13) controlPoint1: NSMakePoint(-1, -12.55) controlPoint2: NSMakePoint(-0.55, -13)];
            [oval17Path curveToPoint: NSMakePoint(1, -12) controlPoint1: NSMakePoint(0.55, -13) controlPoint2: NSMakePoint(1, -12.55)];
            [oval17Path closePath];
            [NSColor.grayColor setFill];
            [oval17Path fill];



            [NSGraphicsContext restoreGraphicsState];
        }
    }
}

+ (void)drawTriggerMetterWithIntensity: (CGFloat)intensity triggerTitle: (NSString*)triggerTitle
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;

    //// Color Declarations
    NSColor* controller = [NSColor colorWithCalibratedRed: 0.232 green: 0.232 blue: 0.232 alpha: 1];
    NSColor* darkController = [controller shadowWithLevel: 0.3];
    NSColor* pressed = [NSColor colorWithCalibratedRed: 1 green: 0.432 blue: 0 alpha: 1];

    //// Variable Declarations
    CGFloat expression = 360 - 270 * intensity - 135;

    //// Oval 18 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 15, 15);

    NSRect oval18Rect = NSMakeRect(-15, -15, 30, 30);
    NSBezierPath* oval18Path = [NSBezierPath bezierPathWithOvalInRect: oval18Rect];
    [controller setFill];
    [oval18Path fill];
    NSMutableParagraphStyle* oval18Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    oval18Style.alignment = NSCenterTextAlignment;

    NSDictionary* oval18FontAttributes = @{NSFontAttributeName: [NSFont fontWithName: @"Arial-Black" size: NSFont.labelFontSize], NSForegroundColorAttributeName: NSColor.whiteColor, NSParagraphStyleAttributeName: oval18Style};

    CGFloat oval18TextHeight = NSHeight([triggerTitle boundingRectWithSize: oval18Rect.size options: NSStringDrawingUsesLineFragmentOrigin attributes: oval18FontAttributes]);
    NSRect oval18TextRect = NSMakeRect(NSMinX(oval18Rect), NSMinY(oval18Rect) + (NSHeight(oval18Rect) - oval18TextHeight) / 2, NSWidth(oval18Rect), oval18TextHeight);
    [NSGraphicsContext saveGraphicsState];
    NSRectClip(oval18Rect);
    [triggerTitle drawInRect: NSOffsetRect(oval18TextRect, 0, 3) withAttributes: oval18FontAttributes];
    [NSGraphicsContext restoreGraphicsState];

    [NSGraphicsContext restoreGraphicsState];


    //// Oval 19 Drawing
    NSBezierPath* oval19Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(4, 4, 22, 22)];
    [darkController setStroke];
    [oval19Path setLineWidth: 1];
    [oval19Path stroke];


    //// Oval 20 Drawing
    NSRect oval20Rect = NSMakeRect(2, 2, 26, 26);
    NSBezierPath* oval20Path = NSBezierPath.bezierPath;
    [oval20Path appendBezierPathWithArcWithCenter: NSMakePoint(NSMidX(oval20Rect), NSMidY(oval20Rect)) radius: NSWidth(oval20Rect) / 2 startAngle: -135 endAngle: expression clockwise: YES];

    [pressed setStroke];
    [oval20Path setLineWidth: 2];
    [oval20Path stroke];


    //// Oval Drawing
    NSRect ovalRect = NSMakeRect(2, 2, 26, 26);
    NSBezierPath* ovalPath = NSBezierPath.bezierPath;
    [ovalPath appendBezierPathWithArcWithCenter: NSMakePoint(NSMidX(ovalRect), NSMidY(ovalRect)) radius: NSWidth(ovalRect) / 2 startAngle: -45 endAngle: -135 clockwise: YES];

    [darkController setStroke];
    [ovalPath setLineWidth: 3.5];
    [ovalPath stroke];
}

+ (void)drawBatteryMonitorWithBars: (CGFloat)bars
{
    //// Color Declarations
    NSColor* buttonB = [NSColor colorWithCalibratedRed: 1 green: 0.094 blue: 0.072 alpha: 1];
    NSColor* controller = [NSColor colorWithCalibratedRed: 0.232 green: 0.232 blue: 0.232 alpha: 1];
    NSColor* darkController = [controller shadowWithLevel: 0.3];

    //// Variable Declarations
    NSColor* batteryColor = bars > 0 ? darkController : buttonB;
    BOOL bar1 = bars > 0;
    BOOL bar2 = bars > 1;
    BOOL bar3 = bars > 2;

    //// Rectangle 3 Drawing
    NSBezierPath* rectangle3Path = NSBezierPath.bezierPath;
    [rectangle3Path moveToPoint: NSMakePoint(1, 2.46)];
    [rectangle3Path curveToPoint: NSMakePoint(2.36, 1) controlPoint1: NSMakePoint(1, 1.65) controlPoint2: NSMakePoint(1.61, 1)];
    [rectangle3Path lineToPoint: NSMakePoint(35.64, 1)];
    [rectangle3Path curveToPoint: NSMakePoint(37, 2.46) controlPoint1: NSMakePoint(36.39, 1) controlPoint2: NSMakePoint(37, 1.65)];
    [rectangle3Path lineToPoint: NSMakePoint(37, 18.54)];
    [rectangle3Path curveToPoint: NSMakePoint(35.64, 20) controlPoint1: NSMakePoint(37, 19.35) controlPoint2: NSMakePoint(36.39, 20)];
    [rectangle3Path lineToPoint: NSMakePoint(2.36, 20)];
    [rectangle3Path curveToPoint: NSMakePoint(1, 18.54) controlPoint1: NSMakePoint(1.61, 20) controlPoint2: NSMakePoint(1, 19.35)];
    [rectangle3Path lineToPoint: NSMakePoint(1, 2.46)];
    [rectangle3Path closePath];
    [batteryColor setStroke];
    [rectangle3Path setLineWidth: 2];
    [rectangle3Path stroke];


    if (bar1)
    {
        //// Rectangle Drawing
        NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(3, 3, 10, 15)];
        [darkController setFill];
        [rectanglePath fill];
    }


    if (bar2)
    {
        //// Rectangle 2 Drawing
        NSBezierPath* rectangle2Path = [NSBezierPath bezierPathWithRect: NSMakeRect(14, 3, 10, 15)];
        [darkController setFill];
        [rectangle2Path fill];
    }


    if (bar3)
    {
        //// Rectangle 4 Drawing
        NSBezierPath* rectangle4Path = [NSBezierPath bezierPathWithRect: NSMakeRect(25, 3, 10, 15)];
        [darkController setFill];
        [rectangle4Path fill];
    }


    //// Rectangle 5 Drawing
    NSBezierPath* rectangle5Path = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(36, 6, 5, 9) xRadius: 1 yRadius: 1];
    [batteryColor setFill];
    [rectangle5Path fill];
}

+ (void)drawDeadZoneViewerWithValue: (CGFloat)value linked: (BOOL)linked
{
    //// Color Declarations
    NSColor* buttonB = [NSColor colorWithCalibratedRed: 1 green: 0.094 blue: 0.072 alpha: 1];

    //// Variable Declarations
    CGFloat width = 64 * value;
    CGFloat center = 32.5 - width / 2.0;
    BOOL circle = linked && value != 0;
    BOOL biSquare = !(value == 0 || linked);

    if (biSquare)
    {
        //// Rectangle Drawing
        NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(center, 0.5, width, 64)];
        [buttonB setStroke];
        [rectanglePath setLineWidth: 2];
        CGFloat rectanglePattern[] = {2, 2};
        [rectanglePath setLineDash: rectanglePattern count: 2 phase: 0];
        [rectanglePath stroke];


        //// Rectangle 2 Drawing
        NSBezierPath* rectangle2Path = [NSBezierPath bezierPathWithRect: NSMakeRect(0.5, center, 64, width)];
        [buttonB setStroke];
        [rectangle2Path setLineWidth: 2];
        CGFloat rectangle2Pattern[] = {2, 2};
        [rectangle2Path setLineDash: rectangle2Pattern count: 2 phase: 0];
        [rectangle2Path stroke];
    }


    if (circle)
    {
        //// Oval Drawing
        NSBezierPath* ovalPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(center, center, width, width)];
        [buttonB setStroke];
        [ovalPath setLineWidth: 2];
        CGFloat ovalPattern[] = {2, 2};
        [ovalPath setLineDash: ovalPattern count: 2 phase: 0];
        [ovalPath stroke];
    }
}

@end
