#!/bin/bash
zip -r ../360ControllerSource.zip *
cd Feedback360
xcodebuild -configuration Deployment
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../DriverTool
xcodebuild -configuration Release
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../360Controller
xcodebuild -configuration Deployment
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../360Daemon
xcodebuild -configuration Release
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../WirelessGamingReceiver
xcodebuild -configuration Release
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../Wireless360Controller
xcodebuild -configuration Release
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../Pref360Control
xcodebuild -configuration Deployment 
if [ $? -ne 0 ]
  then
    echo "******** BUILD FAILED ********"
    exit 1
fi
cd ../Install360Controller
packagesbuild -v Install360Controller.pkgproj
mv build 360ControllerInstall
hdiutil create -srcfolder 360ControllerInstall -format UDZO ../../360ControllerInstall.dmg
mv 360ControllerInstall build
cd ..
echo "** File contents **"
lipo -info 360Controller/build/Deployment/360Controller.kext/Contents/MacOS/360Controller
lipo -info 360Controller/build/Deployment/360Controller.kext/Contents/PlugIns/Feedback360.plugin/Contents/MacOS/Feedback360
lipo -info 360Daemon/build/Release/360Daemon
lipo -info Pref360Control/build/Deployment/Pref360Control.prefPane/Contents/MacOS/Pref360Control
lipo -info Pref360Control/build/Deployment/Pref360Control.prefPane/Contents/Resources/DriverTool
lipo -info WirelessGamingReceiver/build/Release/WirelessGamingReceiver.kext/Contents/MacOS/WirelessGamingReceiver
lipo -info Wireless360Controller/build/Release/Wireless360Controller.kext/Contents/MacOS/Wireless360Controller
echo "** File signatures **"
sudo spctl -a -v 360Controller/build/Deployment/360Controller.kext
sudo spctl -a -v 360Controller/build/Deployment/360Controller.kext/Contents/PlugIns/Feedback360.plugin
sudo spctl -a -v 360Daemon/build/Release/360Daemon
sudo spctl -a -v Pref360Control/build/Deployment/Pref360Control.prefPane
sudo spctl -a -v Pref360Control/build/Deployment/Pref360Control.prefPane/Contents/Resources/DriverTool
sudo spctl -a -v WirelessGamingReceiver/build/Release/WirelessGamingReceiver.kext
sudo spctl -a -v Wireless360Controller/build/Release/Wireless360Controller.kext
sudo spctl -a -v --type install Install360Controller/build/Install360Controller.pkg
echo "*** DONE ***"
